### ISSUE TITLE
Contenerizar la página web

### ISSUE THREAD

**Issue by dcristobalhMad** [cloudnativerioja/official-website#22]
Se propone contenerizar el sitio oficial del community group. En un principio por recursos sería mejor exportar todo como estático y levantarlo con nginx.

**Comment by pabpereza** [comment]
Buenos días, os lanzo ahora una PR con una propuest

**Comment by pabpereza** [comment]
Según donde y como sea el despliegue, habría que añadir algunas configuración al nginx para optimizar caché y demás. Por ejemplo, para mi web personal que se construye también estática con Hugo, añadí estas: https://github.com/pabpereza/pabpereza/tree/main/conf

**Comment by dcristobalhMad** [comment]
Pinta muy bien @pabpereza  🥳
